# Generated by Django 2.0.3 on 2018-03-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, help_text='カウント数')),
                ('msg', models.TextField(blank=True, help_text='メッセージ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'task_b_counter',
                'verbose_name_plural': 'task_b_counters',
                'db_table': 'task_b_counter',
                'managed': True,
            },
        ),
    ]
